name: Clojure CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution: [ 'zulu' ]
        java: [ '11', '17' ]

    name: Java ${{ matrix.Java }} (${{ matrix.distribution }})

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155

      - name: Test with deps
        run: clojure -X:test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy clojars